### ISSUE TITLE
Write paper

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/LocText#9]
- [x] Sketch prepared by Lars: https://docs.google.com/document/d/1GbGbj_0BIWF0L2_jDzbytNyK6TYHHs6AFzQ4AkFe47E/edit#heading=h.t89h7g949bix
- [x] Just new list of authors: https://docs.google.com/document/d/1JTSCi06BfmF9s17TMXea7js5n4NPT0PI9tXBsDlVXQY/edit

**Comment by shpendm** [comment]
I do not have permission on accessing these documents. @juanmirocks please add my gmail account there!

**Comment by juanmirocks** [comment]
# About PhD Thesis !

* Thesis by Tanya: https://mediatum.ub.tum.de/?id=1304188
* How to print: https://wiki.in.tum.de/Informatik/Benutzerwiki/XeroxDrucker

**Comment by juanmirocks** [comment]
Jennifer Boyd, main editor of Bioinformatics for many year (maybe still)

jennifer.boyd@oup.com
